# Generated by Django 3.2.7 on 2021-10-05 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_hotels_tipoturismo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Name')),
                ('descripcion', models.CharField(max_length=30, verbose_name='descripcion')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('valor', models.IntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='authApp.tipoturismo')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Name')),
                ('ubicacion', models.CharField(max_length=30, verbose_name='ubicacion')),
                ('json_fotos', models.CharField(max_length=30, verbose_name='json_fotos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar', to='authApp.tipoturismo')),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Name')),
                ('datos', models.CharField(max_length=30, verbose_name='json_datos')),
                ('foto', models.CharField(max_length=30, verbose_name='foto')),
                ('contacto', models.CharField(max_length=30, verbose_name='telefono')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia', to='authApp.tipoturismo')),
            ],
        ),
    ]
