# Generated by Django 3.2.7 on 2021-10-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_guia_lugar_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guia',
            old_name='tipo',
            new_name='tipo_turismo',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='tipo',
            new_name='tipo_turismo',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='tipo',
            new_name='tipo_turismo',
        ),
    ]
