# Generated by Django 3.2.7 on 2021-10-16 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_auto_20211016_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
